#! lua
local t = require("test")
t.suite("test._bitwise")
t.suite("test._calls")
t.suite("test._close")
t.suite("test._constructs")
t.suite("test._errors")
t.suite("test._goto")
t.suite("test._jsonlib")
t.suite("test._literals")
t.suite("test._main")
t.suite("test._metatables")
t.suite("test._pkgLib")
t.suite("test._stringLib")
t.suite("test._tableLib")
t.suite("test._tmplLib")
t.suite("test._vararg")
t.run({ verbose = os.getenv("VERBOSE") ~= nil })
