local thread = coroutine.create(function()
	print("thread started")
	coroutine.yield(42)
	print("thread ended")
end)

print("resuming")
print(coroutine.resume(thread))
print("yielded")
print(coroutine.resume(thread))
print("done")
