version: "2"
linters:
  default: none
  enable:
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. [auto-fix]
    - goconst # Finds repeated strings that could be replaced by a constant. [fast]
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - govet # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes. [auto-fix]
    - ineffassign # Detects when assignments to existing variables are not used. [fast]
    - staticcheck # It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary. The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint. [auto-fix]
    - unused # Checks Go code for unused constants, variables, functions and types.
    - asasalint # Check for pass []any as any in variadic func(...any).
    - asciicheck # Checks that all code identifiers does not have non-ASCII symbols in the name. [fast]
    - bidichk # Checks for dangerous unicode character sequences. [fast]
    - contextcheck # Check whether the function uses a non-inherited context.
    - copyloopvar # Copyloopvar is a linter detects places where loop variables are copied. [fast]
    - decorder # Check declaration order and count of types, constants, variables and functions. [fast]
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()). [fast]
    - dupword # Checks for duplicate words in the source code. [fast, auto-fix]
    - durationcheck # Check for two durations multiplied together.
    - errchkjson # Checks types passed to the json encoding functions. Reports unsupported types and reports occurrences where the check for the returned error can be omitted.
    - errorlint # Errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13. [auto-fix]
    - exptostd # Detects functions from golang.org/x/exp/ that can be replaced by std functions. [auto-fix]
    - fatcontext # Detects nested contexts in loops and function literals. [auto-fix]
    - forbidigo # Forbids identifiers.
    - ginkgolinter # Enforces standards of using ginkgo and gomega. [auto-fix]
    - gocheckcompilerdirectives # Checks that go compiler directive comments (//go:) are valid. [fast]
    - gochecksumtype # Run exhaustiveness checks on Go "sum types".
    - godot # Check if comments end in a period. [fast, auto-fix]
    - goheader # Checks if file header matches to pattern. [fast, auto-fix]
    - gomoddirectives # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod. [fast]
    - gomodguard # Allow and block list linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations. [fast]
    - goprintffuncname # Checks that printf-like functions are named with `f` at the end. [fast]
    - grouper # Analyze expression groups. [fast]
    - iface # Detect the incorrect use of interfaces, helping developers avoid interface pollution. [auto-fix]
    - importas # Enforces consistent import aliases. [auto-fix]
    - inamedparam # Reports interfaces with unnamed method parameters. [fast]
    - interfacebloat # A linter that checks the number of methods inside an interface. [fast]
    - intrange # Intrange is a linter to find places where for loops could make use of an integer range. [auto-fix]
    - lll # Reports long lines. [fast]
    - loggercheck # Checks key value pairs for common logger libraries (kitlog,klog,logr,zap).
    - makezero # Finds slice declarations with non-zero initial length.
    - mirror # Reports wrong mirror patterns of bytes/strings usage. [auto-fix]
    - misspell # Finds commonly misspelled English words. [fast, auto-fix]
    - musttag # Enforce field tags in (un)marshaled structs.
    - nakedret # Checks that functions with naked returns are not longer than a maximum size (can be zero). [fast, auto-fix]
    - nilerr # Finds the code that returns nil even if it checks that the error is not nil.
    - nilnesserr # This linter reports that it checks for err != nil, but it returns a different nil value error.
    - nolintlint # Reports ill-formed or insufficient nolint directives. [fast, auto-fix]
    - nonamedreturns # Reports all named returns.
    - nosprintfhostport # Checks for misuse of Sprintf to construct a host with port in a URL. [fast]
    - paralleltest # Detects missing usage of t.Parallel() method in your Go test.
    - perfsprint # Checks that fmt.Sprintf can be replaced with a faster alternative. [auto-fix]
    - prealloc # Finds slice declarations that could potentially be pre-allocated. [fast]
    - predeclared # Find code that shadows one of Go's predeclared identifiers. [fast]
    - promlinter # Check Prometheus metrics naming via promlint. [fast]
    - protogetter # Reports direct reads from proto message fields when getters should be used. [auto-fix]
    - reassign # Checks that package variables are not reassigned.
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully.
    - sloglint # Ensure consistent code style when using log/slog.
    - spancheck # Checks for mistakes with OpenTelemetry/Census spans.
    - sqlclosecheck # Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed.
    - tagalign # Check that struct tags are well aligned. [fast, auto-fix]
    - tagliatelle # Checks the struct tags.
    - testableexamples # Linter checks if examples are testable (have an expected output). [fast]
    - testifylint # Checks usage of github.com/stretchr/testify. [auto-fix]
    - thelper # Thelper detects tests helpers which is not start with t.Helper() method.
    - tparallel # Tparallel detects inappropriate usage of t.Parallel() method in your Go test codes.
    - unconvert # Remove unnecessary type conversions.
    - unparam # Reports unused function parameters.
    - usestdlibvars # A linter that detect the possibility to use variables/constants from the Go standard library. [fast, auto-fix]
    - usetesting # Reports uses of functions with replacement inside the testing package. [auto-fix]
    - wastedassign # Finds wasted assignment statements.
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc. [fast, auto-fix]
  exclusions:
    rules:
      - linters:
          - revive
        path: 'src/types/*'
        text: 'var-naming: avoid meaningless package names'
        reason: "It is not a general name in this case, this is a package meant for type definition"
      - linters:
          - revive
        path: 'src/runtime/*'
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
        reason: "It is specifically meant for a language runtime"
      - linters:
          - revive
        path: 'src/parse/*'
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
        reason: "It is specifically meant for a language parser"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
