#!/bin/sh
set -eo pipefail
# Simple script to make examining debug scripts easier and faster
echo "=== Running Debug luaf ==="
filename=$1
if [ "$#" -eq 0 ]; then
	filename=""./test/scratch.lua""
fi
echo "Filename: $filename"
echo "=== Bytecode Listing ==="
go run ./cmd/luaf/main.go -l -p $filename
echo "=== Exec Output ==="
go run ./cmd/luaf/main.go $filename
echo "=== Done Debug luaf ==="
echo "Return Status: $?"
