name: Go
on:
  push: {branches: [ "main" ]}
  pull_request: {branches: [ "main" ]}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    - name: "Set up Go"
      uses: actions/setup-go@v4
      with: {go-version: '1.23'}
    - name: "Go Build"
      run:  go build -v ./cmd/luaf
    - name: "Go Test"
      run:  go test -v ./...
    - name: "e2e Test"
      run:
        - go build -v -o ./luaf ./cmd/luaf
        - ./luaf ./test/all.lua
    - name: "Go Vet"
      run:  go vet ./...
    - name: "golangci-lint"
      uses: golangci/golangci-lint-action@v6
      with: {version: "latest"}
    - name: "Static Check"
      uses: dominikh/staticcheck-action@v1
      with: {version: "latest"}
