name: Go
on:
  push: {branches: [ "main" ]}
  pull_request: {branches: [ "main" ]}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with: {go-version: '1.23'}
    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code
    - name: Go Vet
      run: go vet ./...
    - name: Go Tidy
      run: go mod tidy && git diff --exit-code
    - name: Go Mod
      run: go mod download
    - name: Go Mod Verify
      run: go mod verify
    - name: Go Generate
      run: go generate ./... && git diff --exit-code
    - name: Go Build
      run:  go build -v ./cmd/luaf
    - name: Go Compile Tests
      run: go test -exec /bin/true ./...
    - name: Go Test
      run:  go test -v ./...
    - name: e2e Test
      run: go run ./cmd/luaf -v && echo "done"
